### ISSUE TITLE
[Bug]: Can not use enex2notion command.

### ISSUE THREAD

**Issue by chongiscool** [vzhd1701/enex2notion#40]
### enex2notion version

0.2.15

### What OS are you using?

MacOS

### OS Version / Linux distribution

macOS 10.15.7, 

### Bug description

Homebrew installed it. just run command as below, the output shows some logs as below **Log excerpt** part. 

```bash
# error output
enex2notion --version
```

Installation verbose as following: 

```bash
$ brew install vzhd1701/tap/enex2notion

==> Tapping vzhd1701/tap
Cloning into '/usr/local/Homebrew/Library/Taps/vzhd1701/homebrew-tap'...
remote: Enumerating objects: 104, done.
remote: Counting objects: 100% (104/104), done.
remote: Compressing objects: 100% (83/83), done.
remote: Total 104 (delta 23), reused 90 (delta 15), pack-reused 0
Receiving objects: 100% (104/104), 26.90 KiB | 612.00 KiB/s, done.
Resolving deltas: 100% (23/23), done.
Tapped 3 formulae (17 files, 58.7KB).
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/pkg-config-0.29.2_3.catalina.bottle.tar.gz
######################################################################## 100.0%
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/libpthread-stubs-0.4.catalina.bottle.tar.gz
######################################################################## 100.0%
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/xorgproto-2022.1.catalina.bottle.tar.gz
######################################################################## 100.0%
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/libxau-1.0.9.catalina.bottle.tar.gz
######################################################################## 100.0%
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/libxdmcp-1.1.3.catalina.bottle.tar.gz
######################################################################## 100.0%
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/libxcb-1.15.catalina.bottle.tar.gz
######################################################################## 100.0%
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/libx11-1.8.1.catalina.bottle.tar.gz
######################################################################## 100.0%
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/libxext-1.3.4.catalina.bottle.tar.gz
######################################################################## 100.0%
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/libxfixes-6.0.0.catalina.bottle.tar.gz
######################################################################## 100.0%
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/libxi-1.8.catalina.bottle.tar.gz
######################################################################## 100.0%
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/libxrender-0.9.10.catalina.bottle.tar.gz
######################################################################## 100.0%
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/libxrandr-1.5.2.catalina.bottle.tar.gz
######################################################################## 100.0%
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/libxxf86vm-1.1.4.catalina.bottle.tar.gz
######################################################################## 100.0%
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/expat-2.4.8.catalina.bottle.tar.gz
######################################################################## 100.0%
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/libxdamage-1.1.5.catalina.bottle.tar.gz
######################################################################## 100.0%
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/mesa-22.0.5.catalina.bottle.tar.gz
######################################################################## 100.0%
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/freeglut-3.2.2.catalina.bottle.tar.gz
######################################################################## 100.0%
==> Downloading https://mirrors.ustc.edu.cn/homebrew-bottles/mupdf-1.20.0.catalina.bottle.tar.gz
######################################################################## 100.0%
==> Downloading https://github.com/vzhd1701/homebrew-tap/releases/download/enex2notion-0.2.15/enex2notion-0.2.15.
######################################################################## 100.0%
==> Installing enex2notion from vzhd1701/tap
==> Installing dependencies for vzhd1701/tap/enex2notion: pkg-config, libpthread-stubs, xorgproto, libxau, libxdmcp, libxcb, libx11, libxext, libxfixes, libxi, libxrender, libxrandr, libxxf86vm, expat, libxdamage, mesa, freeglut and mupdf
==> Installing vzhd1701/tap/enex2notion dependency: pkg-config
==> Pouring pkg-config-0.29.2_3.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/pkg-config/0.29.2_3: 11 files, 624.0KB
==> Installing vzhd1701/tap/enex2notion dependency: libpthread-stubs
==> Pouring libpthread-stubs-0.4.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/libpthread-stubs/0.4: 5 files, 6.9KB
==> Installing vzhd1701/tap/enex2notion dependency: xorgproto
==> Pouring xorgproto-2022.1.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/xorgproto/2022.1: 264 files, 3.9MB
==> Installing vzhd1701/tap/enex2notion dependency: libxau
==> Pouring libxau-1.0.9.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/libxau/1.0.9: 20 files, 117.8KB
==> Installing vzhd1701/tap/enex2notion dependency: libxdmcp
==> Pouring libxdmcp-1.1.3.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/libxdmcp/1.1.3: 11 files, 125.4KB
==> Installing vzhd1701/tap/enex2notion dependency: libxcb
==> Pouring libxcb-1.15.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/libxcb/1.15: 2,459 files, 6.9MB
==> Installing vzhd1701/tap/enex2notion dependency: libx11
==> Pouring libx11-1.8.1.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/libx11/1.8.1: 1,055 files, 7MB
==> Installing vzhd1701/tap/enex2notion dependency: libxext
==> Pouring libxext-1.3.4.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/libxext/1.3.4: 87 files, 421KB
==> Installing vzhd1701/tap/enex2notion dependency: libxfixes
==> Pouring libxfixes-6.0.0.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/libxfixes/6.0.0: 12 files, 115.8KB
==> Installing vzhd1701/tap/enex2notion dependency: libxi
==> Pouring libxi-1.8.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/libxi/1.8: 85 files, 671KB
==> Installing vzhd1701/tap/enex2notion dependency: libxrender
==> Pouring libxrender-0.9.10.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/libxrender/0.9.10: 12 files, 170KB
==> Installing vzhd1701/tap/enex2notion dependency: libxrandr
==> Pouring libxrandr-1.5.2.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/libxrandr/1.5.2: 26 files, 205.2KB
==> Installing vzhd1701/tap/enex2notion dependency: libxxf86vm
==> Pouring libxxf86vm-1.1.4.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/libxxf86vm/1.1.4: 33 files, 119.8KB
==> Installing vzhd1701/tap/enex2notion dependency: expat
==> Pouring expat-2.4.8.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/expat/2.4.8: 21 files, 593.9KB
==> Installing vzhd1701/tap/enex2notion dependency: libxdamage
==> Pouring libxdamage-1.1.5.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/libxdamage/1.1.5: 12 files, 81.4KB
==> Installing vzhd1701/tap/enex2notion dependency: mesa
==> Pouring mesa-22.0.5.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/mesa/22.0.5: 36 files, 11.7MB
==> Installing vzhd1701/tap/enex2notion dependency: freeglut
==> Pouring freeglut-3.2.2.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/freeglut/3.2.2: 20 files, 988.2KB
==> Installing vzhd1701/tap/enex2notion dependency: mupdf
==> Pouring mupdf-1.20.0.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/mupdf/1.20.0: 129 files, 48.8MB
==> Installing vzhd1701/tap/enex2notion
==> Pouring enex2notion-0.2.15.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/enex2notion/0.2.15: 1,883 files, 15.4MB
==> Running `brew cleanup enex2notion`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```

### Log excerpt

```shell
cannot create context: incompatible header (1.19.0) and library (1.20.0) versions
Traceback (most recent call last):
  File "/usr/local/bin/enex2notion", line 5, in <module>
    from enex2notion.cli import main
  File "/usr/local/Cellar/enex2notion/0.2.15/libexec/lib/python3.10/site-packages/enex2notion/cli.py", line 9, in <module>
    from enex2notion.cli_upload import EnexUploader
  File "/usr/local/Cellar/enex2notion/0.2.15/libexec/lib/python3.10/site-packages/enex2notion/cli_upload.py", line 9, in <module>
    from enex2notion.note_parser.note import parse_note
  File "/usr/local/Cellar/enex2notion/0.2.15/libexec/lib/python3.10/site-packages/enex2notion/note_parser/note.py", line 12, in <module>
    from enex2notion.note_parser.note_type_based import parse_note_blocks_based_on_type
  File "/usr/local/Cellar/enex2notion/0.2.15/libexec/lib/python3.10/site-packages/enex2notion/note_parser/note_type_based.py", line 8, in <module>
    from enex2notion.note_parser.webclip_pdf import parse_webclip_to_pdf
  File "/usr/local/Cellar/enex2notion/0.2.15/libexec/lib/python3.10/site-packages/enex2notion/note_parser/webclip_pdf.py", line 6, in <module>
    import fitz
  File "/usr/local/Cellar/enex2notion/0.2.15/libexec/lib/python3.10/site-packages/fitz/__init__.py", line 10, in <module>
    from fitz.fitz import *
  File "/usr/local/Cellar/enex2notion/0.2.15/libexec/lib/python3.10/site-packages/fitz/fitz.py", line 15, in <module>
    from . import _fitz
RuntimeError: Fatal error: cannot create global context.
```

**Comment by chongiscool** [comment]
Download this release bin file which works. [bin_enex2notion_0.2.15_macos_x64.zip](https://github.com/vzhd1701/enex2notion/releases/download/v0.2.15/bin_enex2notion_0.2.15_macos_x64.zip)

**Comment by vzhd1701** [comment]
Do you have Apple M1 CPU?

**Comment by chongiscool** [comment]
No, Intel based

**Comment by vzhd1701** [comment]
This should be fixed now. Please try installing it via homebrew again.

**Comment by chongiscool** [comment]
Sorry I am so late to confirm it. Yeah, it did fix. Thanks!

I was checked it after I got email notification at first, it turns seems NOT fixed, even I tried `brew cleanup` and install again, so I let it go. Today I tried again, it works. I don't know why, maybe it's I cleanup again, or maybe I used homebrew mirror which sync is a bit later.
